[package]
name = "trim-logs"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
tempfile = "3.3"
walkdir = "2.3"
rayon = "1.6"
indicatif = "0.17"
clap = { version = "4.1", features = ["derive"] }
