[package]
name = "trim-logs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
env_logger = "0.11"
flate2 = "1.0"
indicatif = "0.17"
log = "0.4"
rayon = "1.6"
tempfile = "3.3"
walkdir = "2.3"
